local g = vim.g
local o = vim.opt

o.backup = false
o.breakindent = true
o.colorcolumn = "100"
o.dir = '/tmp'
o.encoding = "utf-8"
o.expandtab = true
o.hidden = true
o.hlsearch = false
o.ignorecase = true
o.inccommand = 'split'
o.incsearch = true
o.laststatus = 3
o.mouse = "a"
o.nu = true
o.pumheight = 16
o.relativenumber = true
o.scroll = 6
o.scrolloff = 12
o.shiftwidth = 2
o.showmode = false
o.signcolumn = 'yes'
o.smartcase = true
o.splitbelow = true
o.splitright = true
o.swapfile = false
o.swapfile = true
o.tabstop = 2
o.termguicolors = true
o.undodir = os.getenv("HOME") .. "/.vim/undodir"
o.undofile = true
o.updatetime = 250
o.winborder = "single"
o.wrap = false

g.mapleader = ' '
g.maplocalleader = ' '
g.have_nerd_font = true
